# Generated by Django 4.2.3 on 2023-08-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_equipment_needs_repair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='date_bought',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='for_polo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
