# Generated by Django 4.2.3 on 2023-09-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
