# Generated by Django 4.2.3 on 2023-08-16 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('days', models.CharField(choices=[('Sunday', 'Sunday')], max_length=200, null=True)),
                ('time_slot', models.CharField(choices=[('8-10 am', '8-10 am'), ('4-6 pm', '4-6 pm')], max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('days', models.CharField(choices=[('Wednesday', 'Wednesday')], max_length=200, null=True)),
                ('time_slot', models.CharField(choices=[('8-10 am', '8-10 am'), ('4-6 pm', '4-6 pm')], max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('days', models.CharField(choices=[('Saturday', 'Saturday')], max_length=200, null=True)),
                ('time_slot', models.CharField(choices=[('8-10 am', '8-10 am'), ('4-6 pm', '4-6 pm')], max_length=200, null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('riding_field_status', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=20, null=True)),
                ('polo_field_status', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=20, null=True)),
                ('bush_riding_status', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=20, null=True)),
                ('riding_academy_status', models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paystack_charge_id', models.CharField(blank=True, max_length=100)),
                ('paystack_access_code', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activity', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False, null=True)),
                ('date_paid', models.DateTimeField(null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('username', models.CharField(max_length=150, null=True, unique=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('age', models.IntegerField(default=18)),
                ('address', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=150, null=True)),
                ('postal_code', models.CharField(max_length=150, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('duration', models.CharField(max_length=150, null=True)),
                ('explanation', models.CharField(max_length=150, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=150, null=True)),
                ('attendant', models.CharField(max_length=150, null=True)),
                ('customer_fullname', models.CharField(max_length=150, null=True)),
                ('customer_email', models.CharField(max_length=150, null=True)),
                ('customer_number', models.CharField(max_length=150, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.CharField(max_length=150, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.services')),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='member',
            name='slots',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='category',
        ),
        migrations.AddField(
            model_name='member',
            name='activity',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='guardian_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='guardian_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='guardian_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='guardian_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member1_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member1_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member1_city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member1_email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member1_full_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member1_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member1_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member2_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member2_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member2_city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member2_email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member2_full_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member2_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member2_weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='activity',
            field=models.CharField(choices=[('Riding', 'Riding'), ('Polo', 'Polo')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='duration_in_months',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forgetpassword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horses',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.CharField(choices=[(' Monthly', ' Monthly'), (' Yearly', ' Yearly')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Family Riding Monthly', 'Family Riding Monthly'), ('Family Riding Yearly', 'Family Riding Yearly'), ('Family Polo Monthly', 'Family Polo Monthly'), ('Family Polo Yearly', 'Family Polo Yearly'), ('Single Riding Monthly', 'Single Riding Monthly'), ('Single Riding Yearly', 'Single Riding Yearly'), ('Single Polo Monthly', 'Single Polo Monthly'), ('Single Polo Yearly', 'Single Polo Yearly')], max_length=150),
        ),
        migrations.AlterField(
            model_name='slots',
            name='days',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Friday', 'Friday'), ('Wednesday', 'Wednesday'), ('Saturday', 'Saturday')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='payhistory',
            name='payment_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.membership'),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='day1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.day1'),
        ),
        migrations.AddField(
            model_name='member',
            name='day2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.day2'),
        ),
        migrations.AddField(
            model_name='member',
            name='day3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.day3'),
        ),
    ]
