# Generated by Django 4.2.3 on 2023-07-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_day1_day2_day3_services_remove_member_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riding_field_status', models.CharField(max_length=20)),
                ('polo_field_status', models.CharField(max_length=20)),
                ('bush_riding_status', models.CharField(max_length=20)),
                ('riding_academy_status', models.CharField(max_length=20)),
            ],
        ),
    ]
