# Generated by Django 4.2.3 on 2023-07-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='bush_riding_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='polo_field_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='riding_academy_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='riding_field_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Open', 'Open')], max_length=20, null=True),
        ),
    ]
