# Generated by Django 4.2.3 on 2023-07-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='activity',
            field=models.CharField(choices=[('Polo', 'Polo'), ('Riding', 'Riding')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Family', 'Family'), ('Single', 'Single')], max_length=150, unique=True),
        ),
    ]
