# Generated by Django 4.2.3 on 2023-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_membership_activity_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Family', 'Family'), ('Single', 'Single')], max_length=150),
        ),
    ]
