# Generated by Django 4.2.3 on 2023-07-31 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_membership_membership_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='duration',
            new_name='duration_in_months',
        ),
    ]
