# Generated by Django 4.2.3 on 2023-07-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_membership_duration_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='activity',
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Family Polo', 'Family Polo'), ('Single Riding', 'Single Riding')], max_length=150),
        ),
    ]
