# Generated by Django 4.2.3 on 2023-08-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_membership_activity_alter_membership_membership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='paid',
        ),
    ]
