# Generated by Django 4.2.3 on 2023-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_payhistory_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='activity',
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Family Riding Monthly', 'Family Riding Monthly'), ('Family Riding Yearly', 'Family Riding Yearly'), ('Family Polo Monthly', 'Family Polo Monthly'), ('Family Polo Yearly', 'Family Polo Yearly'), ('Single Riding Monthly', 'Single Riding Monthly'), ('Single Riding Yearly', 'Single Riding Yearly'), ('Single Polo Monthly', 'Single Polo Monthly'), ('Single Polo Yearly', 'Single Polo Yearly')], max_length=150),
        ),
    ]
