# Generated by Django 4.2.3 on 2023-08-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_membership_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='activity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='paystack_access_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='paystack_charge_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
