# Generated by Django 4.2.3 on 2023-08-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_payhistory_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='duration_in_months',
        ),
        migrations.AddField(
            model_name='membership',
            name='activity',
            field=models.CharField(choices=[('Riding', 'Riding'), ('Polo', 'Polo')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='duration',
            field=models.CharField(choices=[(' Monthly', ' Monthly'), (' Yearly', ' Yearly')], max_length=150, null=True),
        ),
    ]
