# Generated by Django 4.2.3 on 2023-08-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_membership_duration_in_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activity',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
