# Generated by Django 4.2.3 on 2023-08-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_member_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
