# Generated by Django 4.2.3 on 2023-08-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_payhistory_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='duration_in_months',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
