# Generated by Django 4.2.3 on 2023-08-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_membership_duration_in_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='date_paid',
            field=models.DateTimeField(null=True),
        ),
    ]
