# Generated by Django 4.2.3 on 2023-08-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_payhistory_date_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
