# Generated by Django 4.2.3 on 2023-08-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
