# Generated by Django 4.2.3 on 2023-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_payhistory_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='suspend',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
