# Generated by Django 4.2.3 on 2023-08-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_member_suspend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='suspend',
            field=models.BooleanField(default=False),
        ),
    ]
