# Generated by Django 4.2.3 on 2023-08-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_member_suspend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member1_name',
            new_name='member1_email',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='member2_name',
            new_name='member1_full_name',
        ),
        migrations.AddField(
            model_name='member',
            name='member2_email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='member2_full_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
