# Generated by Django 4.2.3 on 2023-08-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_member1_name_member_member1_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='date',
        ),
        migrations.AddField(
            model_name='payhistory',
            name='days_remainig',
            field=models.IntegerField(null=True),
        ),
    ]
