# Generated by Django 4.2.3 on 2023-08-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_payhistory_date_payhistory_days_remainig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='days_remainig',
        ),
    ]
