# Generated by Django 4.2.3 on 2023-08-16 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('accounts', '0002_day1_day2_day3_field_notification_payhistory_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgetpassword',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payhistory',
            name='payment_for',
        ),
        migrations.RemoveField(
            model_name='payhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='member',
            name='day1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.day1'),
        ),
        migrations.AlterField(
            model_name='member',
            name='day2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.day2'),
        ),
        migrations.AlterField(
            model_name='member',
            name='day3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.day3'),
        ),
        migrations.DeleteModel(
            name='Day1',
        ),
        migrations.DeleteModel(
            name='Day2',
        ),
        migrations.DeleteModel(
            name='Day3',
        ),
        migrations.DeleteModel(
            name='ForgetPassword',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PayHistory',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
