# Generated by Django 4.2.3 on 2023-08-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
