# Generated by Django 4.2.3 on 2023-08-16 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
