# Generated by Django 4.2.3 on 2023-08-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_day3_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day3',
            name='name',
            field=models.CharField(choices=[('Saturday Morning', 'Saturday Morning'), ('Saturday Morning', 'Saturday Morning'), ('Sunday Morning', 'Sunday Morning'), ('Sunday Morning', 'Sunday Morning'), ('Wednesday Morning', 'Wednesday Morning'), ('Wednesday Morning', 'Wednesday Morning'), ('Friday Morning', 'Friday Morning'), ('Friday Morning', 'Friday Morning')], max_length=200, null=True),
        ),
    ]
