# Generated by Django 4.2.3 on 2023-08-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_day3_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day3',
            name='name',
            field=models.CharField(choices=[('Saturday Morning', 'Saturday Morning'), ('Saturday Evening', 'Saturday Evening'), ('Sunday Morning', 'Sunday Morning'), ('Sunday Evening', 'Sunday Evening'), ('Wednesday Morning', 'Wednesday Morning'), ('Wednesday Evening', 'Wednesday Evening'), ('Friday Morning', 'Friday Morning'), ('Friday Evening', 'Friday Evening')], max_length=200, null=True),
        ),
    ]
