# Generated by Django 4.2.3 on 2023-08-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_day1_days_alter_day1_name_alter_day2_days_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day3',
            new_name='Days',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='day3',
            new_name='days',
        ),
        migrations.RemoveField(
            model_name='member',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='member',
            name='day2',
        ),
        migrations.DeleteModel(
            name='Day1',
        ),
        migrations.DeleteModel(
            name='Day2',
        ),
    ]
