# Generated by Django 4.2.3 on 2023-08-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_features_membership_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='activity',
            field=models.CharField(choices=[('POLO', 'POLO'), ('RIDING', 'RIDING')], max_length=150, null=True),
        ),
    ]
