# Generated by Django 4.2.3 on 2023-08-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_features_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='forgetpassword',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
