# Generated by Django 4.2.3 on 2023-08-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_member22'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member22',
        ),
    ]
