# Generated by Django 4.2.3 on 2023-08-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_support_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_ticket',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
