# Generated by Django 4.2.3 on 2023-08-20 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_support_ticket_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support_Ticket',
        ),
    ]
