# Generated by Django 4.2.3 on 2023-08-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_delete_support_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
